unit BrotliDecoder;

// Author: www.xelitan.com
// License: MIT

{$mode Delphi}
{$H+}
{$POINTERMATH ON}

interface

uses SysUtils, BrotliBase, BrotliBitReader, BrotliHuffman;

type
  TBrotliDecoderResult = (
    BROTLI_DECODER_RESULT_ERROR = 0,
    BROTLI_DECODER_RESULT_SUCCESS = 1,
    BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT = 2,
    BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT = 3
  );

  TBrotliDecoderErrorCode = (
    BROTLI_DECODER_NO_ERROR = 0,
    BROTLI_DECODER_SUCCESS = 1,
    BROTLI_DECODER_NEEDS_MORE_INPUT = 2,
    BROTLI_DECODER_NEEDS_MORE_OUTPUT = 3,
    BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE = -1,
    BROTLI_DECODER_ERROR_FORMAT_RESERVED = -2,
    BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE = -3,
    BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET = -4,
    BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME = -5,
    BROTLI_DECODER_ERROR_FORMAT_CL_SPACE = -6,
    BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE = -7,
    BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT = -8,
    BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1 = -9,
    BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2 = -10,
    BROTLI_DECODER_ERROR_FORMAT_TRANSFORM = -11,
    BROTLI_DECODER_ERROR_FORMAT_DICTIONARY = -12,
    BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS = -13,
    BROTLI_DECODER_ERROR_FORMAT_PADDING_1 = -14,
    BROTLI_DECODER_ERROR_FORMAT_PADDING_2 = -15,
    BROTLI_DECODER_ERROR_FORMAT_DISTANCE = -16,
    BROTLI_DECODER_ERROR_COMPOUND_DICTIONARY = -18,
    BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET = -19,
    BROTLI_DECODER_ERROR_INVALID_ARGUMENTS = -20,
    BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES = -21,
    BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS = -22,
    BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP = -25,
    BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1 = -26,
    BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2 = -27,
    BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES = -30,
    BROTLI_DECODER_ERROR_UNREACHABLE = -31
  );

  TBrotliRunningState = (
    BROTLI_STATE_UNINITED,
    BROTLI_STATE_LARGE_WINDOW_BITS,
    BROTLI_STATE_INITIALIZE,
    BROTLI_STATE_METABLOCK_BEGIN,
    BROTLI_STATE_METABLOCK_HEADER,
    BROTLI_STATE_METABLOCK_HEADER_2,
    BROTLI_STATE_CONTEXT_MODES,
    BROTLI_STATE_COMMAND_BEGIN,
    BROTLI_STATE_COMMAND_INNER,
    BROTLI_STATE_COMMAND_POST_DECODE_LITERALS,
    BROTLI_STATE_COMMAND_POST_WRAP_COPY,
    BROTLI_STATE_UNCOMPRESSED,
    BROTLI_STATE_METADATA,
    BROTLI_STATE_COMMAND_INNER_WRITE,
    BROTLI_STATE_METABLOCK_DONE,
    BROTLI_STATE_COMMAND_POST_WRITE_1,
    BROTLI_STATE_COMMAND_POST_WRITE_2,
    BROTLI_STATE_BEFORE_COMPRESSED_METABLOCK_HEADER,
    BROTLI_STATE_HUFFMAN_CODE_0,
    BROTLI_STATE_HUFFMAN_CODE_1,
    BROTLI_STATE_HUFFMAN_CODE_2,
    BROTLI_STATE_HUFFMAN_CODE_3,
    BROTLI_STATE_CONTEXT_MAP_1,
    BROTLI_STATE_CONTEXT_MAP_2,
    BROTLI_STATE_TREE_GROUP,
    BROTLI_STATE_BEFORE_COMPRESSED_METABLOCK_BODY,
    BROTLI_STATE_DONE
  );

  PBrotliDecoderState = ^TBrotliDecoderState;
  TBrotliDecoderState = record
    state: TBrotliRunningState;
    br: TBrotliBitReader;
    error_code: LongInt;
    window_bits: uint32_t;
    large_window: BROTLI_BOOL;
    used_input: uint64_t;
  end;

function BrotliDecoderCreateInstance: PBrotliDecoderState;
procedure BrotliDecoderDestroyInstance(state: PBrotliDecoderState);
function BrotliDecoderDecompress(encoded_size: size_t; encoded_buffer: PByte; var decoded_size: size_t; decoded_buffer: PByte): TBrotliDecoderResult;
function BrotliDecoderGetErrorCode(state: PBrotliDecoderState): TBrotliDecoderErrorCode;
function BrotliDecoderErrorString(c: TBrotliDecoderErrorCode): PAnsiChar;
function BrotliDecoderVersion: uint32_t;

implementation

const
  BrotliDecoderVersionValue = $01010100; { 1.1.0 }

function BrotliDecoderCreateInstance: PBrotliDecoderState;
begin
  New(Result);
  FillChar(Result^, SizeOf(Result^), 0);
  Result^.state := BROTLI_STATE_UNINITED;
  Result^.error_code := Ord(BROTLI_DECODER_NO_ERROR);
  BrotliInitBitReader(@Result^.br);
end;

procedure BrotliDecoderDestroyInstance(state: PBrotliDecoderState);
begin
  if state <> nil then Dispose(state);
end;

function BrotliDecoderDecompress(encoded_size: size_t; encoded_buffer: PByte; var decoded_size: size_t; decoded_buffer: PByte): TBrotliDecoderResult;
begin
  { This unit intentionally does not bind to libbrotli. The public wrapper is
    present so application code can be wired while the large decode.c state
    machine is being ported. }
  decoded_size := 0;
  Result := BROTLI_DECODER_RESULT_ERROR;
end;

function BrotliDecoderGetErrorCode(state: PBrotliDecoderState): TBrotliDecoderErrorCode;
begin
  if state = nil then Exit(BROTLI_DECODER_ERROR_INVALID_ARGUMENTS);
  Result := TBrotliDecoderErrorCode(state^.error_code);
end;

function BrotliDecoderErrorString(c: TBrotliDecoderErrorCode): PAnsiChar;
begin
  case c of
    BROTLI_DECODER_NO_ERROR: Result := 'NO_ERROR';
    BROTLI_DECODER_SUCCESS: Result := 'SUCCESS';
    BROTLI_DECODER_NEEDS_MORE_INPUT: Result := 'NEEDS_MORE_INPUT';
    BROTLI_DECODER_NEEDS_MORE_OUTPUT: Result := 'NEEDS_MORE_OUTPUT';
    BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE: Result := 'FORMAT_EXUBERANT_NIBBLE';
    BROTLI_DECODER_ERROR_FORMAT_RESERVED: Result := 'FORMAT_RESERVED';
    BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE: Result := 'FORMAT_EXUBERANT_META_NIBBLE';
    BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET: Result := 'FORMAT_SIMPLE_HUFFMAN_ALPHABET';
    BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME: Result := 'FORMAT_SIMPLE_HUFFMAN_SAME';
    BROTLI_DECODER_ERROR_FORMAT_CL_SPACE: Result := 'FORMAT_CL_SPACE';
    BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE: Result := 'FORMAT_HUFFMAN_SPACE';
    BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT: Result := 'FORMAT_CONTEXT_MAP_REPEAT';
    BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1: Result := 'FORMAT_BLOCK_LENGTH_1';
    BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2: Result := 'FORMAT_BLOCK_LENGTH_2';
    BROTLI_DECODER_ERROR_FORMAT_TRANSFORM: Result := 'FORMAT_TRANSFORM';
    BROTLI_DECODER_ERROR_FORMAT_DICTIONARY: Result := 'FORMAT_DICTIONARY';
    BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS: Result := 'FORMAT_WINDOW_BITS';
    BROTLI_DECODER_ERROR_FORMAT_PADDING_1: Result := 'FORMAT_PADDING_1';
    BROTLI_DECODER_ERROR_FORMAT_PADDING_2: Result := 'FORMAT_PADDING_2';
    BROTLI_DECODER_ERROR_FORMAT_DISTANCE: Result := 'FORMAT_DISTANCE';
    BROTLI_DECODER_ERROR_COMPOUND_DICTIONARY: Result := 'COMPOUND_DICTIONARY';
    BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET: Result := 'DICTIONARY_NOT_SET';
    BROTLI_DECODER_ERROR_INVALID_ARGUMENTS: Result := 'INVALID_ARGUMENTS';
    BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES: Result := 'ALLOC_CONTEXT_MODES';
    BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS: Result := 'ALLOC_TREE_GROUPS';
    BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP: Result := 'ALLOC_CONTEXT_MAP';
    BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1: Result := 'ALLOC_RING_BUFFER_1';
    BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2: Result := 'ALLOC_RING_BUFFER_2';
    BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES: Result := 'ALLOC_BLOCK_TYPE_TREES';
    BROTLI_DECODER_ERROR_UNREACHABLE: Result := 'UNREACHABLE';
  else
    Result := 'UNKNOWN';
  end;
end;

function BrotliDecoderVersion: uint32_t;
begin
  Result := BrotliDecoderVersionValue;
end;

end.
